// Code generated by msggen from locales/*.toml. DO NOT EDIT.

package locales

import (
	"context"

	"github.com/joeblew999/go-htmx4/kit/i18n"
	"github.com/joeblew999/go-htmx4/kit/i18n/cldr"
)

func defaultLocale() *i18n.Locale { return cldr.Data.MustLocale(catalogs[0].Locale) }

// Messages are the app's UI strings in one locale. Get them with For (the request's locale) or ForLocale.
type Messages struct {
	loc *i18n.Locale
	cat *i18n.Catalog
}

// For returns the messages for the request's locale (kit/i18n FromContext), or the source locale's.
func For(ctx context.Context) Messages {
	if r, ok := i18n.FromContext(ctx); ok {
		return ForLocale(r.Locale)
	}
	return Messages{cat: catalogs[0]}
}

// ForLocale returns the messages for a resolved locale (the source locale's for one without a catalog).
func ForLocale(loc *i18n.Locale) Messages {
	for _, c := range catalogs {
		if loc != nil && c.Locale == loc.Data.ID {
			return Messages{loc: loc, cat: c}
		}
	}
	return Messages{loc: loc, cat: catalogs[0]}
}

// Pseudo returns en-XA pseudo-localized messages (accented, bracketed, ~40% longer) formatted with loc's
// rules: render pages with them to find text that doesn't go through a catalog.
func Pseudo(loc *i18n.Locale) Messages { return Messages{loc: loc, cat: pseudoCatalog} }

// Complete reports whether the locale's catalog translates every message.
func Complete(id string) bool {
	for i, c := range catalogs {
		if c.Locale == id {
			return complete[i]
		}
	}
	return false
}

func (m Messages) format(i int, args ...i18n.MsgArgValue) string {
	loc := m.loc
	if loc == nil {
		loc = defaultLocale()
	}
	return loc.FormatMessage(m.cat.Messages[i].Parts, args...)
}
