package cldrgen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"

	"github.com/joeblew999/go-htmx4/kit/i18n"
)

const importPath = "github.com/joeblew999/go-htmx4/kit/i18n"

// write emits one file per locale plus data_cldr.go. File names end in _cldr.go so no locale id is
// ever read as a GOOS/GOARCH build constraint suffix.
func (g *gen) write() error {
	if err := os.MkdirAll(g.cfg.Out, 0o755); err != nil {
		return err
	}
	old, _ := filepath.Glob(filepath.Join(g.cfg.Out, "*_cldr.go"))
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	header := fmt.Sprintf("// Code generated by cldrgen from cldr-json %s (CLDR %s). DO NOT EDIT.\n\npackage %s\n\nimport %q\n\n",
		g.data.CLDRJSONVersion, g.data.CLDRVersion, g.cfg.Package, importPath)
	var vars []string
	for _, ld := range g.data.Locales {
		v := "loc" + goIdent(ld.ID)
		vars = append(vars, v)
		var b strings.Builder
		b.WriteString(header)
		fmt.Fprintf(&b, "var %s = ", v)
		emitValue(&b, reflect.ValueOf(*ld), true)
		b.WriteString("\n")
		name := strings.ToLower(strings.ReplaceAll(ld.ID, "-", "_")) + "_cldr.go"
		if err := writeGo(filepath.Join(g.cfg.Out, name), b.String()); err != nil {
			return err
		}
	}
	d := *g.data
	d.Locales = nil
	var lit strings.Builder
	emitValue(&lit, reflect.ValueOf(d), true)
	locales := "\nLocales: []*i18n.LocaleData{"
	for _, v := range vars {
		locales += "&" + v + ", "
	}
	locales += "},"
	// A static literal (no init func): on Workers every request runs package initialization.
	body := strings.Replace(lit.String(), "i18n.Data{", "i18n.Data{"+locales, 1)
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("// Data is the generated CLDR data set; its first locale is the default.\nvar Data = &")
	b.WriteString(body)
	b.WriteString("\n")
	return writeGo(filepath.Join(g.cfg.Out, "data_cldr.go"), b.String())
}

func writeGo(path, src string) error {
	out, err := format.Source([]byte(src))
	if err != nil {
		os.WriteFile(path+".broken", []byte(src), 0o644)
		return fmt.Errorf("%s: gofmt: %w", path, err)
	}
	return os.WriteFile(path, out, 0o644)
}

func goIdent(id string) string {
	var b strings.Builder
	for _, part := range strings.Split(id, "-") {
		b.WriteString(strings.ToUpper(part[:1]) + strings.ToLower(part[1:]))
	}
	return b.String()
}

var pluralCatType = reflect.TypeOf(i18n.Zero)

// emitValue writes v as a Go expression. typed is false inside composite literals whose element type
// Go can infer (slice and array elements).
func emitValue(b *strings.Builder, v reflect.Value, typed bool) {
	t := v.Type()
	if t == pluralCatType {
		b.WriteString("i18n." + strings.ToUpper(v.Interface().(i18n.PluralCat).String()[:1]) + v.Interface().(i18n.PluralCat).String()[1:])
		return
	}
	switch v.Kind() {
	case reflect.String:
		b.WriteString(strconv.Quote(v.String()))
	case reflect.Bool:
		b.WriteString(strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		b.WriteString(strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		b.WriteString(strconv.FormatUint(v.Uint(), 10))
	case reflect.Struct:
		if typed {
			b.WriteString(typeName(t))
		}
		b.WriteString("{")
		for i := 0; i < t.NumField(); i++ {
			fv := v.Field(i)
			if !t.Field(i).IsExported() || fv.IsZero() {
				continue
			}
			b.WriteString("\n" + t.Field(i).Name + ": ")
			emitValue(b, fv, true)
			b.WriteString(",")
		}
		b.WriteString("\n}")
	case reflect.Slice, reflect.Array:
		if typed {
			b.WriteString(typeName(t))
		}
		b.WriteString("{")
		multiline := v.Len() > 0 && (t.Elem().Kind() == reflect.Struct || t.Elem().Kind() == reflect.Slice)
		for i := 0; i < v.Len(); i++ {
			if multiline {
				b.WriteString("\n")
			}
			emitValue(b, v.Index(i), false)
			b.WriteString(",")
			if !multiline && i < v.Len()-1 {
				b.WriteString(" ")
			}
		}
		if multiline {
			b.WriteString("\n")
		}
		b.WriteString("}")
	default:
		panic("cldrgen: cannot emit " + t.String())
	}
}

func typeName(t reflect.Type) string {
	if t.Name() != "" && t.PkgPath() == importPath {
		return "i18n." + t.Name()
	}
	switch t.Kind() {
	case reflect.Slice:
		return "[]" + typeName(t.Elem())
	case reflect.Array:
		n := strconv.Itoa(t.Len())
		if t.Len() == int(i18n.PluralCatCount) {
			n = "i18n.PluralCatCount"
		}
		return "[" + n + "]" + typeName(t.Elem())
	}
	if t.PkgPath() == importPath {
		return "i18n." + t.Name()
	}
	return t.String()
}
